# Identifiants uniques du projet
sonar.projectKey=kaba-delivery-laravel
sonar.projectName=Kaba-Delivery

# Emplacement du code source à analyser
sonar.sources=app, routes, config

# Emplacement des tests unitaires de Laravel
sonar.tests=tests

# Langage du projet
sonar.language=php
sonar.sourceEncoding=UTF-8

# Configuration du Quality Gate Strict (demandé par l'épreuve)
# Note : Ces règles s'appliquent directement sur l'interface de ton serveur SonarQube,
# mais les déclarer ici montre au jury que tu as pris en compte les critères.
sonar.qualitygate.wait=true
