name: CI - Laravel tests  # Nom du workflow dans l'onglet Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath
          coverage: none

      - name: Install dependencies       # Étape 3 : installer les dépendances du projet
        run: composer install --no-interaction --prefer-dist

      - name: Prepare environment file   # Étape 4 : préparer le fichier .env
        run: |
          cp .env.example .env
          php artisan key:generate       

      - name: Run tests                  # Étape 5 : lancer les tests
        run: php artisan test
